name: Quality assurance

on: push

jobs:
  eslint:
    name: ESLint
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@master

    - name: Setup Node.js
      uses: actions/setup-node@master
      with:
        node-version: '14.x'

    - name: Install npm dependencies
      run: npm ci

    - name: Lint with ESLint
      run: npx eslint .
